### PR TITLE
Remove jQuery selectors and methods

### PR DESCRIPTION
**Pull request by valexiev**
Make it with standard JavaScript and Angular so there is no need for jQuery.

### CODE REVIEW

**Comment by harm-less** [comment]
Thanks for your pull request. It was on my to-do list to see if I could only make it only depend on jqLite.
I'll merge this pull tomorrow as well.

**Comment by harm-less** [comment]
Btw, in the karma config file a reference to jQuery is still there. Can you create another commit with this reference removed to see if the plugin would still pass in Travis CI?

**Comment by harm-less** [comment]
Hey, I ran the pull through Karma with jQuery removed from ```karma.conf.js```, but this breaks it as I was afraid of.
I think this needs to be fixed if this pull-request will make any sense, what about you?

**Comment by harm-less** [comment]
I'm not entirely sure what you meant with your line comment. But I don't think Karma is necessarily dependent on jQuery. It's just that the current state of the code (even with your changes), without jQuery it doesn't pass.
But if those errors can be fixed, the resulting build will be an Angular Sticky that will work without jQuery.

**Comment by codeuniquely** [comment]
Can this branch be integrated please - ???

**Pull request merged**
