### PR TITLE
Added enable flag to allow for toggling sticky behavior

### PR DESCRIPTION
**Pull request by psaniko**
We need to toggle sticky behavior on/off based on different conditions. Would you be willing to integrate this change and if so could you check if the PR needs any more adjustments?

### CODE REVIEW

**Comment by harm-less** [comment]
Oh, nice feature ;)

From the looks of it the changes seem good, though I'm not sure if they work in every situation. I'm not sure if it also works if you toggle the ```enable``` back to ```true``` for example. But like I said, that's only from looking at the code instead of actually testing it myself. 
That having said, can you make a couple of unit test that accompany your feature? Let me know if you need any help with that.

**Comment by harm-less** [comment]
And let's not forget the documentation as well. But I can do that for you if you like.

**Comment by psaniko** [comment]
Wanted to see if you like the impementation first :) 

Added tests and documentation. Sorry for the commit confusion, I switched between work and personal.

**Comment by harm-less** [comment]
Good call ;)

Thanks for the additions, it's starting to take shape. The unit tests probably cover all your code, but not on the services necessarily. The "hlSticky" directive I think is covered very nicely, but the following services are not yet covered:
- https://github.com/harm-less/angular-sticky/blob/master/tests/angular-sticky.spec.js#L360 
- https://github.com/harm-less/angular-sticky/blob/master/tests/angular-sticky.spec.js#L940

And btw, now that I think about it. What happens if you have a stack of 3 and the second on is turned off?

**Comment by psaniko** [comment]
Thanks for pointing that out, I missed that. Should now be fixed and I also added some more tests.

**Comment by harm-less** [comment]
Looks good now from what I can see from the code! Hopefully within a few hours I can review it in more detail. Otherwise it will be tonight.

But once again, thanks for the feature ;)

**Comment by harm-less** [comment]
All right, everything is done! Great feature mate ;)

It has been release in version ```0.3.0```, cheers.

**Pull request merged**
