### PR TITLE
Updated sticky

### PR DESCRIPTION
**Pull request by phazei**
- Fixes the demo page.
- Refactors the way options are submitted with clear defaults and ability to use a option config object on the directive.
- Fixes handling of offsetBottom when attached top and offsetTop when attached bottom.
- Adds classes attached to object for before it goes sticky, and after it goes sticky
- Adds zIndex option
- Adds tests

### CODE REVIEW

**Comment by harm-less** [comment]
Hey @phazei ,

Thanks for the elaborate PR. I do have to take some time to look at the changes in more detail, but so far it looks good.
Already one thing came up I'm wondering about, is the plugin itself still functional without jQuery?

**Comment by phazei** [comment]
I didn't add anything that was jQuery dependent.  First I backed off the angular version since the demo uses some stuff that was deprecated in angular 7, and there was some other error with angular 6.  It might work with 5, but I figured just go back to the version the demo worked on.

Something does appear to have a jQuery dependency because after getting rid of the errors from the angular version, it was still getting some and I was comparing the commits where it first started, and it was when jQuery was removed.  I think it's just the demo app itself that has the dependency since the tests pass without jQuery

**Comment by phazei** [comment]
bump

**Comment by phazei** [comment]
want to merge this?

**Comment by harm-less** [comment]
Hey mate,
Sorry for the long wait, it's been the first time since a few months I actually spend some time programming and maintaining my repos at home.

Anyway, I hope the merge isn't too late for your intends and purposes and I've made a new release from your changes (0.5.0).
A month ago I was telling a colleague about this project and when I showed him the demos I noticed they weren't working, so that was unhandy... So again, many thanks for the improvements! 😄

**Pull request merged**
